# Generated by Django 4.2.19 on 2025-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='datadevolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='dataemprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
