# Generated by Django 4.2.19 on 2025-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimos_datadevolucao_emprestimos_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='matricula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
