# Generated by Django 4.2.19 on 2025-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_alunos_matricula_alter_livros_ano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
        migrations.RenameModel(
            old_name='Emprestimos',
            new_name='Emprestimo',
        ),
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
